### 
POST {{deploy}}/addNodeId
content-type: application/json

{
"publicKey": "...", 
"timestamp": "...", 
"signature": "..."
}
### 
POST {{deploy}}/getSecretSpace
content-type: application/json

{
"publicKey": "...", 
"timestamp": "...", 
"signature": "..."
}
### 
POST {{deploy}}/getSecret
content-type: application/json

{
"publicKey": "...", 
"secretId": "...", 
"timestamp": "...", 
"signature": "..."
}
### 
POST {{deploy}}/setSecret
content-type: application/json

{
"publicKey": "...", 
"secretId": "...", 
"secret": "...", 
"timestamp": "...", 
"signature": "..."
}
### 
POST {{deploy}}/deleteSecret
content-type: application/json

{
"publicKey": "...", 
"secretId": "...", 
"timestamp": "...", 
"signature": "..."
}
### 
POST {{deploy}}/startAcceptingSecretsFrom
content-type: application/json

{
"publicKey": "...", 
"fromId": "...", 
"timestamp": "...", 
"signature": "..."
}
### 
POST {{deploy}}/stopAcceptingSecretsFrom
content-type: application/json

{
"publicKey": "...", 
"fromId": "...", 
"timestamp": "...", 
"signature": "..."
}
### 
POST {{deploy}}/shareSecretTo
content-type: application/json

{
"publicKey": "...", 
"shareToId": "...", 
"secretId": "...", 
"secret": "...", 
"timestamp": "...", 
"signature": "..."
}
### 
POST {{deploy}}/deleteSharedSecret
content-type: application/json

{
"publicKey": "...", 
"sharedToId": "...", 
"secretId": "...", 
"timestamp": "...", 
"signature": "..."
}
### 
POST {{deploy}}/addSyncHook
content-type: application/json

{
"publicKey": "...", 
"secretId": "...", 
"serverURL": "...", 
"timestamp": "...", 
"signature": "..."
}
### 
POST {{deploy}}/addNotificationHook
content-type: application/json

{
"publicKey": "...", 
"type": "...", 
"specific": "...", 
"timestamp": "...", 
"signature": "..."
}
### 
POST {{deploy}}/getAuthCode
content-type: application/json

{
"publicKey": "...", 
"timestamp": "...", 
"signature": "..."
}
### 
POST {{deploy}}/addFriendServer
content-type: application/json

{
"authCode": "...", 
"serverURL": "...", 
"serverNodeId": "..."
}
### 
POST {{deploy}}/getNodeId
content-type: application/json

{
"authCode": "..."
}
