### 
POST {{local}}/addNodeId
content-type: application/json

{
"publicKey": "...", 
"timestamp": "...", 
"signature": "..."
}
### 
POST {{local}}/getSecretSpace
content-type: application/json

{
"publicKey": "...", 
"timestamp": "...", 
"signature": "..."
}
### 
POST {{local}}/getSecret
content-type: application/json

{
"publicKey": "...", 
"secretId": "...", 
"timestamp": "...", 
"signature": "..."
}
### 
POST {{local}}/setSecret
content-type: application/json

{
"publicKey": "...", 
"secretId": "...", 
"secret": "...", 
"timestamp": "...", 
"signature": "..."
}
### 
POST {{local}}/deleteSecret
content-type: application/json

{
"publicKey": "...", 
"secretId": "...", 
"timestamp": "...", 
"signature": "..."
}
### 
POST {{local}}/startAcceptingSecretsFrom
content-type: application/json

{
"publicKey": "...", 
"fromId": "...", 
"timestamp": "...", 
"signature": "..."
}
### 
POST {{local}}/stopAcceptingSecretsFrom
content-type: application/json

{
"publicKey": "...", 
"fromId": "...", 
"timestamp": "...", 
"signature": "..."
}
### 
POST {{local}}/shareSecretTo
content-type: application/json

{
"publicKey": "...", 
"shareToId": "...", 
"secretId": "...", 
"secret": "...", 
"timestamp": "...", 
"signature": "..."
}
### 
POST {{local}}/deleteSharedSecret
content-type: application/json

{
"publicKey": "...", 
"sharedToId": "...", 
"secretId": "...", 
"timestamp": "...", 
"signature": "..."
}
### 

POST {{local}}/addNotificationHook
content-type: application/json

{
"publicKey": "...", 
"type": "...", 
"specific": "...", 
"timestamp": "...", 
"signature": "..."
}
### 
POST {{local}}/getAuthCode
content-type: application/json

{
"publicKey": "...", 
"timestamp": "...", 
"signature": "..."
}
### 
POST {{local}}/addFriendServer
content-type: application/json

{
"authCode": "...", 
"serverURL": "...", 
"serverNodeId": "..."
}
### 
POST {{local}}/getNodeId
content-type: application/json

{
"authCode": "..."
}
